version: '4.18.0'

networks:
  default:

services:
  db:
    image: mysql:8.0.32
    container_name: lot_database
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./mysql:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: lot_database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      restart: always

  app:
    build: .
    container_name: lot_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/lot_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DATABASE_USER=root
      - DATABASE_PASS=pass
      - JAVA_OPTS=-Xmx300m -Xms300m
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: lot_swagger
    ports:
      - "80:8080"
    environment:
      SWAGGER_JSON: /docs/api-docs.yaml
    volumes:
      - "./api-docs.yaml:/docs/api-docs.yaml"
    restart: always

